# Generated by Django 5.0.1 on 2024-02-18 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesfactures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesfactures', models.FileField(upload_to='mesfactures')),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesfactures',
                'verbose_name_plural': 'Mesfactures',
            },
        ),
    ]
