# Generated by Django 5.0.1 on 2024-02-18 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0003_alter_mesfactures_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesfactures',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
