# Generated by Django 5.0.1 on 2024-02-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0005_masignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masignature',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kapver_app.employer'),
        ),
    ]
