# Generated by Django 5.0.1 on 2024-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0006_alter_masignature_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masignature',
            name='sig',
            field=models.ImageField(upload_to='signature_travailleur'),
        ),
    ]
