# Generated by Django 5.0.1 on 2024-03-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kapver_app", "0007_alter_masignature_sig"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("adresse", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("code_pays", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Collaborateur",
                "verbose_name_plural": "Collaborateurs",
            },
        ),
        migrations.CreateModel(
            name="GriseSalariale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="salaire")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="ficheemployer",
            old_name="heurejour",
            new_name="arbeitszeit1",
        ),
        migrations.RemoveField(
            model_name="ficheemployer",
            name="arbeitszeit",
        ),
        migrations.RemoveField(
            model_name="ficheemployer",
            name="semaine",
        ),
        migrations.AddField(
            model_name="ficheemployer",
            name="arbeitszeit2",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ficheemployer",
            name="pause",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ficheemployer",
            name="stunden",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
