# Generated by Django 5.0.1 on 2024-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kapver_app", "0008_collaborateur_grisesalariale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesfactures",
            name="confirm",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="facturier",
            name="einzelpreis",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="facturier",
            name="menge",
            field=models.FloatField(),
        ),
    ]
