# Generated by Django 5.0.1 on 2024-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kapver_app", "0009_mesfactures_confirm_alter_facturier_einzelpreis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiche",
            name="approuver",
            field=models.BooleanField(default=False),
        ),
    ]
