# Generated by Django 5.0.1 on 2024-04-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kapver_app", "0010_fiche_approuver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dokumente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("doc", models.FileField(upload_to="dokument")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Dokumente",
                "verbose_name_plural": "Dokumentes",
            },
        ),
    ]
