# Generated by Django 5.0.1 on 2024-08-05 19:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0012_conge_demande_conges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
