# Generated by Django 5.0.1 on 2024-08-06 15:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0013_alter_offre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapver_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('specialisation', ckeditor.fields.RichTextField()),
                ('recrutement_international', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='CritereSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere', models.CharField(max_length=255)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='kapver_app.entreprise')),
            ],
        ),
    ]
