# Generated by Django 5.0.1 on 2024-08-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0015_kapver_info_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteresatisfaction',
            name='entreprise',
        ),
    ]
