# Generated by Django 5.0.1 on 2024-08-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0016_remove_criteresatisfaction_entreprise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CritereSatisfaction',
        ),
    ]
