# Generated by Django 5.0.1 on 2024-08-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0018_criteresatisfaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kapver_info',
            name='description',
        ),
    ]
