# Generated by Django 5.0.1 on 2024-08-06 18:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0019_remove_kapver_info_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caroussel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Caroussel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('description1', ckeditor.fields.RichTextField()),
                ('description2', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
