# Generated by Django 5.0.1 on 2024-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0020_caroussel1_caroussel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroussel1',
            name='image_caroussel1',
            field=models.ImageField(blank=True, null=True, upload_to='caroussel1'),
        ),
        migrations.AddField(
            model_name='caroussel2',
            name='image_caroussel2',
            field=models.ImageField(blank=True, null=True, upload_to='caroussel2'),
        ),
    ]
