# Generated by Django 5.0.1 on 2024-08-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0022_kapver_info_critere_delete_criteresatisfaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caroussel1',
            new_name='Banniere1',
        ),
        migrations.RenameModel(
            old_name='Caroussel2',
            new_name='Banniere2',
        ),
    ]
