# Generated by Django 5.0.1 on 2024-08-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapver_app', '0002_load_initial_data'),
        ('kapver_app', '0023_rename_caroussel1_banniere1_and_more'),
    ]

    operations = [
    ]
